# Generated by Django 2.1.2 on 2018-11-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_gen_party1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gen',
            name='party1',
        ),
        migrations.AddField(
            model_name='gen',
            name='total',
            field=models.IntegerField(default='0'),
        ),
    ]
